COLLECTION = {
    11: ("Alice's Adventures in Wonderland", "Children / Young Adult"),
    12: ("Through the Looking-Glass", "Children / Young Adult"),
    16: ("Peter Pan", "Children / Young Adult"),
    55: ("The Wonderful Wizard of Oz", "Children / Young Adult"),
    113: ("The Secret Garden", "Children / Young Adult"),
    120: ("Treasure Island", "Children / Young Adult"),
    236: ("The Jungle Book", "Children / Young Adult"),
    108: ("The Return of Sherlock Holmes", "Crime, Mystery & Thriller"),
    834: ("The Memoirs of Sherlock Holmes", "Crime, Mystery & Thriller"),
    863: ("The Mysterious Affair at Styles", "Crime, Mystery & Thriller"),
    1661: ("The Adventures of Sherlock Holmes", "Crime, Mystery & Thriller"),
    61262: ("Poirot Investigates", "Crime, Mystery & Thriller"),
    69087: ("The Murder of Roger Ackroyd", "Crime, Mystery & Thriller"),
    70114: ("The Big Four", "Crime, Mystery & Thriller"),
    35: ("The Time Machine", "Science-Fiction & Fantasy"),
    36: ("The War of the Worlds", "Science-Fiction & Fantasy"),
    84: ("Frankenstein; Or, The Modern Prometheus", "Science-Fiction & Fantasy"),
    159: ("The Island of Doctor Moreau", "Science-Fiction & Fantasy"),
    164: ("Twenty Thousand Leagues under the Sea", "Science-Fiction & Fantasy"),
    345: ("Dracula", "Science-Fiction & Fantasy"),
    68283: ("The Call of Cthulhu", "Science-Fiction & Fantasy"),
}
